---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: assistant-ui
  namespace: demo-int-admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assistant-ui-config
  namespace: demo-int-admin
data:
  QUARKUS_APPLICATION_VERSION: "1.0.0"
  QUARKUS_HTTP_PORT: "8081"
  QUARKUS_QUTE_STRICT_RENDERING: "false"
  ASSISTANT_API_URL: "http://assistant-api.demo-int-admin.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistant-ui
  namespace: demo-int-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assistant-ui
  template:
    metadata:
      labels:
        app: assistant-ui
    spec:
      serviceAccountName: assistant-ui
      containers:
        - name: app
          image: quay.io/sergio_canales_e/iadmin/assistant-ui:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: assistant-ui-config
---
apiVersion: v1
kind: Service
metadata:
  name: assistant-ui
  namespace: demo-int-admin
spec:
  selector:
    app: assistant-ui
  ports:
    - name: http
      port: 80
      targetPort: 8081
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: assistant-ui
  namespace: demo-int-admin
spec:
  to:
    kind: Service
    name: assistant-ui
  port:
    targetPort: http
